
ifeq ($(MAKECMDGOALS),)
ifeq ($(ENV),development)
DEFAULT ?= 
endif
ifeq ($(ENV),testing)
DEFAULT ?= build test
endif
ifeq ($(ENV),production)
DEFAULT ?= build install check
endif
endif

ifeq ($(MAKECMDGOALS),test)
ifeq ($(ENV),development)
DEFAULT ?= test
endif
ifeq ($(ENV),testing)
DEFAULT ?= test install check
endif
#ifeq ($(ENV),production)
#DEFAULT ?= test install check
#endif
endif

